### PR TITLE
Add variable --kickstart to reanaconda

### PR DESCRIPTION
**Pull request by t184256**
Inspired by a request in https://github.com/OpenSCAP/oscap-anaconda-addon/pull/144. Wasn't properly tested yet, but at least I see it trying to parse the contents of what I supply with `--kickstart`.

@matejak, did I understand the request correctly?

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
@jkonecny12, how do you want to handle this? Given this is a project of @t184256, I would not be opposed to merging once he thinks this is ready...

**Comment by t184256** [comment]
I don't mind waiting until @matejak tries it out. This little project of mine has some disconnect between the user needs and what I thought the user needs were, so I'd like some feedback to prevent this gap from growing further.

**Comment by matejak** [comment]
I have checked it out, and it works great, and it brings our addon development to the next level. The PR provides great value as-is.

What would you think of priming with the variable kickstart on by default, and providing some placeholder when it is not supplied during the `update` invocation? That could improve the UX as people wouldn't have to think much what to opt in during priming, and they could start to use the feature as soon as they find out that they need it during the testing itself.

I have tried to run previously primed Fedora setup with the `--kickstart` option, and the tool was caught by surprise that the server was asked for `/` and it didn't count with that.

**Comment by jkonecny12** [comment]
I agree @VladimirSlavik . So please @t184256 , just tell us when we should hit the merge button :)

**Comment by t184256** [comment]
Hm, OK! Please take a look at another iteration. Hope supplying an all-whitespace kickstart is not much more different from not supplying one at all.

Changes since e23c833:
* have `--variable-kickstart` implied as part of `--sensible`
* `updates` with no `--kickstart` results in serving `\n` as the kickstart file context and printing a hint on how does one supply a real one.


Some behaviour I found that might be of interest to Anaconda devs:
* 404 (`--kickstart /nonexisting`) - prints a `Warning: anaconda: failed to fetch kickstart from ...`, then stalls for quite a while, then drops into an emergency shell
* 0-byte kickstart (`--kickstart /dev/null`) - proceeds after something inside anaconda tracebacks because ks file apparently is not created, then reaches tmux, complains about it the second time and halts.

**Comment by t184256** [comment]
I've discussed that today with @jkonecny12 and @poncovka and had to reverse my course.

Turns out even supplying an all-whitespace kickstart file sets an `automatedInstall` flag inside anaconda, influencing quite a lot of aspects of the internal behaviour. Such an partial-automated mode is not a good replacement for no kickstart and defaulting to it doesn't sound reasonable. There doesn't seem to be a way to "oops-didn't-mean-to-pass-a-kickstart" and so I'm afraid there isn't a way to prime in a way that suits both kickstart and no-kickstart cases. I've reverted the latest changes and added a prominent warning that suggests `--variable-kickstart` to those using `--sensible` early on.

I believe this PR is now adequately tested and can be merged; if somebody figures out how to improve UX or unify priming, we can have another one.

**Pull request merged**
